version: '2'
services:
  webapp:
    image: samarth/samarth-webapp:v0.1.0
    build: 
      #context: ./
      context: https://github.com/stackroute/Samarth-Candidate.git#dev-wave-10
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    expose:
      - 8080
    ports:
      - "80:8080"
  platform:
    image: samarth/samarth-platform:v0.1.0
    build: 
      #context: ../Samarth-Platform
      context: https://github.com/stackroute/Samarth-Platform.git#dev-wave-10
      dockerfile: Dockerfile
    network_mode: host
    restart: always
    expose:
      - 8081
    ports:
      - "80:8081"
  